---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rng
  namespace: rng
  labels:
    app.kubernetes.io/name: rng
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: rng
