---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rng
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rng
  targetCPUUtilizationPercentage: 70
