---
name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_NAME: limelight

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: [ "1.16", "1.17" ]
    env:
      GIN_MODE: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-${{ matrix.go }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.go }}-go-
      - run: go mod download
      - run: go mod verify
      - run: go build -v ./...
      - run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      GIN_MODE: release
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/${{ github.actor }}/${{ env.PROJECT_NAME }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=sha,prefix=,suffix=,format=long
            type=sha,prefix=,suffix=,format=short
      - uses: docker/build-push-action@v2
        id: build
        with:
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=ghcr.io/${{ github.actor }}/${{ env.PROJECT_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.actor }}/${{ env.PROJECT_NAME }}:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo ${{ steps.build.outputs.digest }}
      - uses: azure/container-scan@v0.1
        continue-on-error: true
        with:
          image-name: ghcr.io/${{ github.actor }}/${{ env.PROJECT_NAME }}

  # verify:
  #   name: Verify
  #   runs-on: ubuntu-20.04
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: helm/kind-action@v1.2.0
  #     - run: kubectl apply -f manifests
  #     - run: kubectl delete -f manifests
