---
name: CI

on: [push, pull_request, workflow_dispatch]

env:
  PROJECT_NAME: rng
  REGISTRY_URL: registry.hub.docker.com

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ "1.16", "1.17" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go mod download
      - run: go build -v ./...
      - run: go test -v ./...

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [ "1.16", "1.17" ]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.REGISTRY_NAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          logout: true
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ${{ env.REGISTRY_URL }}/${{ secrets.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}
          flavor: |
            latest=true
            prefix=
            suffix=
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha,prefix=,suffix=,format=long
            type=sha,prefix=,suffix=,format=short
            type=raw,value=${{ matrix.environment }}
      - uses: docker/build-push-action@v2
        id: build
        with:
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=${{ env.REGISTRY_URL }}/${{ secrets.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_URL }}/${{ secrets.REGISTRY_NAME }}/${{ env.PROJECT_NAME }}:buildcache,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - run: echo ${{ steps.build.outputs.digest }}
